version: "3.1"

networks:
  web:
    external: true

services:
  saved:
    build: .
    container_name: saved
    restart: always
    environment:
      - SERVER_PORT=3333
      - DEBUG=false
      - NODE_ENV=production
      - MONGO_DB=wbag
      - MONGO_ADDRS=mongodb:27017
    labels:
      - "traefik.backend=saved"
      - "traefik.domain=kumpf.io"
      - "traefik.frontend.rule=Host:saved.kumpf.io"
      - "traefik.frontend.redirect.entryPoint=https"
      - "traefik.docker.network=web"
      - "traefik.port=3333"
    networks:
      - web
