version: "3.1"

networks:
  web:
    external: true

services:
  wbag:
    build: .
    container_name: wbag
    ports:
      - "3334:3334"
    environment:
      - SERVER_PORT=3334
      - DEBUG=true
      - NODE_ENV=development
      - MONGO_DB=wbag
      - MONGO_ADDRS=mongodev:27017
    labels:
      - traefik.enable=false
    networks:
      - web

  mongodev:
    image: mongodb:latest
    container_name: mongodev
    command: mongod --smallfiles
    volumes:
      - ../mongo:/data/db
    labels:
      - traefik.enable=false
    networks:
      - web

